### PR TITLE
improve the youtube scraper based on PyVideo maintainer comments

### PR DESCRIPTION
**Pull request by piotrbulinski**
Improvements based on the comments from: https://github.com/pyvideo/pyvideo-data/pull/132

### CODE REVIEW

**Comment by piotrbulinski** [comment]
please don't merge it yet, need to fix one more issue

**Comment by piotrbulinski** [comment]
ready to be merged

**Comment by slick666** [comment]
LGTM

**Comment by paulcollinsiii** [comment]
heads up, I've force pushed this branch after rebasing to get rid of the merge commit in this branch. I need to add a contributing doc here which I'll get up in a PR soon for people to see. Otherwise looks good to me

**Pull request merged**
